apiVersion: v1
kind: Service
metadata:
  name: go-web-app
spec:
  selector:
    app.kubernetes.io/name: go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080



###real one 
apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-web-app
  type: NodePort
